Update 1-tbd.yml

diff --git a/.github/workflows/1-tbd.yml b/.github/workflows/1-tbd.yml
--- a/.github/workflows/1-tbd.yml
+++ b/.github/workflows/1-tbd.yml
@@ -7,7 +7,6 @@ on:
 
 permissions: write-all
 
-
 jobs:
   check-solution:
     runs-on: ubuntu-latest
@@ -40,9 +39,22 @@ jobs:
           issue-number: ${{ github.event.pull_request.number }}
           assessment: ${{ needs.check-solution.outputs.assessment }}
           reason: ${{ needs.check-solution.outputs.reason }}
-  update-step:
+  evaluate-assessment:
     runs-on: ubuntu-latest
     needs: check-solution
+    steps:
+      - name: Check Assessment
+        if: needs.check-solution.outputs.assessment == 'correct'
+        run: echo "Your submission is correct. Continue to the next step."
+
+      - name: Fail Assessment
+        if: needs.check-solution.outputs.assessment != 'correct'
+        run: |
+          echo "Your submission is missing something. Please review the comments."
+          exit 1
+  update-step:
+    runs-on: ubuntu-latest
+    needs: evaluate-assessment
     if: needs.check-solution.outputs.assessment == 'correct'
     steps:
       - name: Checkout
